# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20230518

from __future__ import absolute_import

from .adb_dedicated_auto_create_tablespace_details import ADBDedicatedAutoCreateTablespaceDetails
from .adb_dedicated_remap_target_tablespace_details import ADBDedicatedRemapTargetTablespaceDetails
from .adb_serverles_tablespace_details import ADBServerlesTablespaceDetails
from .admin_credentials import AdminCredentials
from .advisor_check_summary import AdvisorCheckSummary
from .advisor_report import AdvisorReport
from .advisor_report_bucket_details import AdvisorReportBucketDetails
from .advisor_report_check_collection import AdvisorReportCheckCollection
from .advisor_report_check_column import AdvisorReportCheckColumn
from .advisor_report_check_object_summary import AdvisorReportCheckObjectSummary
from .advisor_report_check_objects_collection import AdvisorReportCheckObjectsCollection
from .advisor_report_check_summary import AdvisorReportCheckSummary
from .advisor_report_location_details import AdvisorReportLocationDetails
from .affected_objects_collection import AffectedObjectsCollection
from .all_update_advisor_report_check_objects_details import AllUpdateAdvisorReportCheckObjectsDetails
from .all_update_check_action_update_object_details import AllUpdateCheckActionUpdateObjectDetails
from .assessment import Assessment
from .assessment_collection import AssessmentCollection
from .assessment_object_collection import AssessmentObjectCollection
from .assessment_object_type_summary import AssessmentObjectTypeSummary
from .assessment_object_type_summary_collection import AssessmentObjectTypeSummaryCollection
from .assessment_summary import AssessmentSummary
from .assessor import Assessor
from .assessor_action import AssessorAction
from .assessor_check import AssessorCheck
from .assessor_check_action import AssessorCheckAction
from .assessor_check_group import AssessorCheckGroup
from .assessor_check_name_value import AssessorCheckNameValue
from .assessor_check_summary import AssessorCheckSummary
from .assessor_check_summary_collection import AssessorCheckSummaryCollection
from .assessor_group import AssessorGroup
from .assessor_summary import AssessorSummary
from .assessor_summary_collection import AssessorSummaryCollection
from .change_assessment_compartment_details import ChangeAssessmentCompartmentDetails
from .change_connection_compartment_details import ChangeConnectionCompartmentDetails
from .change_migration_compartment_details import ChangeMigrationCompartmentDetails
from .clone_assessment_details import CloneAssessmentDetails
from .clone_migration_details import CloneMigrationDetails
from .collect_traces_data import CollectTracesData
from .collect_traces_details import CollectTracesDetails
from .connection import Connection
from .connection_collection import ConnectionCollection
from .connection_summary import ConnectionSummary
from .create_adb_dedicated_auto_create_tablespace_details import CreateADBDedicatedAutoCreateTablespaceDetails
from .create_adb_dedicated_remap_target_tablespace_details import CreateADBDedicatedRemapTargetTablespaceDetails
from .create_adb_serverles_tablespace_details import CreateADBServerlesTablespaceDetails
from .create_admin_credentials import CreateAdminCredentials
from .create_assessment_details import CreateAssessmentDetails
from .create_connection_details import CreateConnectionDetails
from .create_curl_transfer_details import CreateCurlTransferDetails
from .create_data_pump_parameters import CreateDataPumpParameters
from .create_directory_object import CreateDirectoryObject
from .create_extract import CreateExtract
from .create_golden_gate_hub_details import CreateGoldenGateHubDetails
from .create_host_dump_transfer_details import CreateHostDumpTransferDetails
from .create_migration_details import CreateMigrationDetails
from .create_my_sql_advisor_settings import CreateMySqlAdvisorSettings
from .create_my_sql_assessment_details import CreateMySqlAssessmentDetails
from .create_my_sql_data_transfer_medium_details import CreateMySqlDataTransferMediumDetails
from .create_my_sql_ggs_deployment_details import CreateMySqlGgsDeploymentDetails
from .create_my_sql_initial_load_settings import CreateMySqlInitialLoadSettings
from .create_my_sql_migration_details import CreateMySqlMigrationDetails
from .create_my_sql_object_storage_data_transfer_medium_details import CreateMySqlObjectStorageDataTransferMediumDetails
from .create_mysql_connection_details import CreateMysqlConnectionDetails
from .create_non_adb_auto_create_tablespace_details import CreateNonADBAutoCreateTablespaceDetails
from .create_non_adb_remap_tablespace_details import CreateNonADBRemapTablespaceDetails
from .create_object_store_bucket import CreateObjectStoreBucket
from .create_oci_cli_dump_transfer_details import CreateOciCliDumpTransferDetails
from .create_oracle_advisor_settings import CreateOracleAdvisorSettings
from .create_oracle_assessment_details import CreateOracleAssessmentDetails
from .create_oracle_aws_s3_data_transfer_medium_details import CreateOracleAwsS3DataTransferMediumDetails
from .create_oracle_connection_details import CreateOracleConnectionDetails
from .create_oracle_data_transfer_medium_details import CreateOracleDataTransferMediumDetails
from .create_oracle_db_link_data_transfer_medium_details import CreateOracleDbLinkDataTransferMediumDetails
from .create_oracle_ggs_deployment_details import CreateOracleGgsDeploymentDetails
from .create_oracle_initial_load_settings import CreateOracleInitialLoadSettings
from .create_oracle_migration_details import CreateOracleMigrationDetails
from .create_oracle_nfs_data_transfer_medium_details import CreateOracleNfsDataTransferMediumDetails
from .create_oracle_object_storage_data_transfer_medium_details import CreateOracleObjectStorageDataTransferMediumDetails
from .create_parameter_file_version_details import CreateParameterFileVersionDetails
from .create_replicat import CreateReplicat
from .create_target_type_tablespace_details import CreateTargetTypeTablespaceDetails
from .curl_transfer_details import CurlTransferDetails
from .data_pump_parameters import DataPumpParameters
from .database_connection_type_collection import DatabaseConnectionTypeCollection
from .database_connection_type_summary import DatabaseConnectionTypeSummary
from .database_information import DatabaseInformation
from .database_technology_sub_type import DatabaseTechnologySubType
from .database_technology_type import DatabaseTechnologyType
from .diagnostics_result import DiagnosticsResult
from .directory_object import DirectoryObject
from .download_sql_details import DownloadSqlDetails
from .excluded_object_summary import ExcludedObjectSummary
from .excluded_object_summary_collection import ExcludedObjectSummaryCollection
from .extract import Extract
from .ggs_deployment import GgsDeployment
from .golden_gate_hub_details import GoldenGateHubDetails
from .host_dump_transfer_details import HostDumpTransferDetails
from .ingress_ip_details import IngressIpDetails
from .job import Job
from .job_collection import JobCollection
from .job_output_summary import JobOutputSummary
from .job_output_summary_collection import JobOutputSummaryCollection
from .job_summary import JobSummary
from .list_update_advisor_report_check_objects_details import ListUpdateAdvisorReportCheckObjectsDetails
from .list_update_check_action_update_object_details import ListUpdateCheckActionUpdateObjectDetails
from .log_location_bucket_details import LogLocationBucketDetails
from .metadata_remap import MetadataRemap
from .migration import Migration
from .migration_collection import MigrationCollection
from .migration_job_progress_resource import MigrationJobProgressResource
from .migration_job_progress_summary import MigrationJobProgressSummary
from .migration_object_collection import MigrationObjectCollection
from .migration_object_type_summary import MigrationObjectTypeSummary
from .migration_object_type_summary_collection import MigrationObjectTypeSummaryCollection
from .migration_parameter_base import MigrationParameterBase
from .migration_parameter_details import MigrationParameterDetails
from .migration_parameter_summary import MigrationParameterSummary
from .migration_parameter_summary_collection import MigrationParameterSummaryCollection
from .migration_phase_collection import MigrationPhaseCollection
from .migration_phase_summary import MigrationPhaseSummary
from .migration_summary import MigrationSummary
from .my_sql_advisor_settings import MySqlAdvisorSettings
from .my_sql_assessment import MySqlAssessment
from .my_sql_assessment_object_collection import MySqlAssessmentObjectCollection
from .my_sql_assessment_summary import MySqlAssessmentSummary
from .my_sql_clone_assessment_details import MySqlCloneAssessmentDetails
from .my_sql_clone_migration_details import MySqlCloneMigrationDetails
from .my_sql_data_transfer_medium_details import MySqlDataTransferMediumDetails
from .my_sql_database_object import MySqlDatabaseObject
from .my_sql_database_object_summary import MySqlDatabaseObjectSummary
from .my_sql_ggs_deployment_details import MySqlGgsDeploymentDetails
from .my_sql_initial_load_settings import MySqlInitialLoadSettings
from .my_sql_migration import MySqlMigration
from .my_sql_migration_object_collection import MySqlMigrationObjectCollection
from .my_sql_migration_summary import MySqlMigrationSummary
from .my_sql_object_storage_data_transfer_medium_details import MySqlObjectStorageDataTransferMediumDetails
from .mysql_connection import MysqlConnection
from .mysql_connection_summary import MysqlConnectionSummary
from .name_value_pair import NameValuePair
from .non_adb_auto_create_tablespace_details import NonADBAutoCreateTablespaceDetails
from .non_adb_remap_tablespace_details import NonADBRemapTablespaceDetails
from .object_metadata import ObjectMetadata
from .object_store_bucket import ObjectStoreBucket
from .oci_cli_dump_transfer_details import OciCliDumpTransferDetails
from .oracle_advisor_settings import OracleAdvisorSettings
from .oracle_assessment import OracleAssessment
from .oracle_assessment_object_collection import OracleAssessmentObjectCollection
from .oracle_assessment_summary import OracleAssessmentSummary
from .oracle_aws_s3_data_transfer_medium_details import OracleAwsS3DataTransferMediumDetails
from .oracle_clone_assessment_details import OracleCloneAssessmentDetails
from .oracle_clone_migration_details import OracleCloneMigrationDetails
from .oracle_connection import OracleConnection
from .oracle_connection_summary import OracleConnectionSummary
from .oracle_data_transfer_medium_details import OracleDataTransferMediumDetails
from .oracle_database_object import OracleDatabaseObject
from .oracle_database_object_summary import OracleDatabaseObjectSummary
from .oracle_db_link_data_transfer_medium_details import OracleDbLinkDataTransferMediumDetails
from .oracle_ggs_deployment_details import OracleGgsDeploymentDetails
from .oracle_initial_load_settings import OracleInitialLoadSettings
from .oracle_migration import OracleMigration
from .oracle_migration_object_collection import OracleMigrationObjectCollection
from .oracle_migration_summary import OracleMigrationSummary
from .oracle_nfs_data_transfer_medium_details import OracleNfsDataTransferMediumDetails
from .oracle_object_storage_data_transfer_medium_details import OracleObjectStorageDataTransferMediumDetails
from .parameter_file_version import ParameterFileVersion
from .parameter_file_version_collection import ParameterFileVersionCollection
from .parameter_file_version_summary import ParameterFileVersionSummary
from .perform_assessor_action_details import PerformAssessorActionDetails
from .perform_assessor_check_action_details import PerformAssessorCheckActionDetails
from .phase_extract_entry import PhaseExtractEntry
from .phase_status import PhaseStatus
from .replicat import Replicat
from .result_error import ResultError
from .resume_job_details import ResumeJobDetails
from .source_assessment_connection import SourceAssessmentConnection
from .start_migration_details import StartMigrationDetails
from .target_assessment_connection import TargetAssessmentConnection
from .target_type_tablespace_details import TargetTypeTablespaceDetails
from .unsupported_database_object import UnsupportedDatabaseObject
from .update_adb_dedicated_auto_create_tablespace_details import UpdateADBDedicatedAutoCreateTablespaceDetails
from .update_adb_dedicated_remap_target_tablespace_details import UpdateADBDedicatedRemapTargetTablespaceDetails
from .update_adb_serverles_tablespace_details import UpdateADBServerlesTablespaceDetails
from .update_admin_credentials import UpdateAdminCredentials
from .update_advisor_report_check_details import UpdateAdvisorReportCheckDetails
from .update_advisor_report_check_objects_details import UpdateAdvisorReportCheckObjectsDetails
from .update_assessment_details import UpdateAssessmentDetails
from .update_check_action_update_object_details import UpdateCheckActionUpdateObjectDetails
from .update_connection_details import UpdateConnectionDetails
from .update_curl_transfer_details import UpdateCurlTransferDetails
from .update_data_pump_parameters import UpdateDataPumpParameters
from .update_directory_object import UpdateDirectoryObject
from .update_extract import UpdateExtract
from .update_golden_gate_hub_details import UpdateGoldenGateHubDetails
from .update_host_dump_transfer_details import UpdateHostDumpTransferDetails
from .update_job_details import UpdateJobDetails
from .update_migration_details import UpdateMigrationDetails
from .update_my_sql_advisor_settings import UpdateMySqlAdvisorSettings
from .update_my_sql_assessment_details import UpdateMySqlAssessmentDetails
from .update_my_sql_data_transfer_medium_details import UpdateMySqlDataTransferMediumDetails
from .update_my_sql_ggs_deployment_details import UpdateMySqlGgsDeploymentDetails
from .update_my_sql_initial_load_settings import UpdateMySqlInitialLoadSettings
from .update_my_sql_migration_details import UpdateMySqlMigrationDetails
from .update_my_sql_object_storage_data_transfer_medium_details import UpdateMySqlObjectStorageDataTransferMediumDetails
from .update_mysql_connection_details import UpdateMysqlConnectionDetails
from .update_non_adb_auto_create_tablespace_details import UpdateNonADBAutoCreateTablespaceDetails
from .update_non_adb_remap_tablespace_details import UpdateNonADBRemapTablespaceDetails
from .update_object_store_bucket import UpdateObjectStoreBucket
from .update_oci_cli_dump_transfer_details import UpdateOciCliDumpTransferDetails
from .update_oracle_advisor_settings import UpdateOracleAdvisorSettings
from .update_oracle_assessment_details import UpdateOracleAssessmentDetails
from .update_oracle_aws_s3_data_transfer_medium_details import UpdateOracleAwsS3DataTransferMediumDetails
from .update_oracle_connection_details import UpdateOracleConnectionDetails
from .update_oracle_data_transfer_medium_details import UpdateOracleDataTransferMediumDetails
from .update_oracle_db_link_data_transfer_medium_details import UpdateOracleDbLinkDataTransferMediumDetails
from .update_oracle_ggs_deployment_details import UpdateOracleGgsDeploymentDetails
from .update_oracle_initial_load_settings import UpdateOracleInitialLoadSettings
from .update_oracle_migration_details import UpdateOracleMigrationDetails
from .update_oracle_nfs_data_transfer_medium_details import UpdateOracleNfsDataTransferMediumDetails
from .update_oracle_object_storage_data_transfer_medium_details import UpdateOracleObjectStorageDataTransferMediumDetails
from .update_replicat import UpdateReplicat
from .update_target_defaults_auto_create_tablespace_details import UpdateTargetDefaultsAutoCreateTablespaceDetails
from .update_target_defaults_remap_tablespace_details import UpdateTargetDefaultsRemapTablespaceDetails
from .update_target_type_tablespace_details import UpdateTargetTypeTablespaceDetails
from .user_defined_properties import UserDefinedProperties
from .user_defined_property import UserDefinedProperty
from .user_defined_property_option import UserDefinedPropertyOption
from .work_request import WorkRequest
from .work_request_collection import WorkRequestCollection
from .work_request_error import WorkRequestError
from .work_request_error_collection import WorkRequestErrorCollection
from .work_request_log_entry import WorkRequestLogEntry
from .work_request_log_entry_collection import WorkRequestLogEntryCollection
from .work_request_resource import WorkRequestResource
from .work_request_summary import WorkRequestSummary

# Maps type names to classes for database_migration services.
database_migration_type_mapping = {
    "ADBDedicatedAutoCreateTablespaceDetails": ADBDedicatedAutoCreateTablespaceDetails,
    "ADBDedicatedRemapTargetTablespaceDetails": ADBDedicatedRemapTargetTablespaceDetails,
    "ADBServerlesTablespaceDetails": ADBServerlesTablespaceDetails,
    "AdminCredentials": AdminCredentials,
    "AdvisorCheckSummary": AdvisorCheckSummary,
    "AdvisorReport": AdvisorReport,
    "AdvisorReportBucketDetails": AdvisorReportBucketDetails,
    "AdvisorReportCheckCollection": AdvisorReportCheckCollection,
    "AdvisorReportCheckColumn": AdvisorReportCheckColumn,
    "AdvisorReportCheckObjectSummary": AdvisorReportCheckObjectSummary,
    "AdvisorReportCheckObjectsCollection": AdvisorReportCheckObjectsCollection,
    "AdvisorReportCheckSummary": AdvisorReportCheckSummary,
    "AdvisorReportLocationDetails": AdvisorReportLocationDetails,
    "AffectedObjectsCollection": AffectedObjectsCollection,
    "AllUpdateAdvisorReportCheckObjectsDetails": AllUpdateAdvisorReportCheckObjectsDetails,
    "AllUpdateCheckActionUpdateObjectDetails": AllUpdateCheckActionUpdateObjectDetails,
    "Assessment": Assessment,
    "AssessmentCollection": AssessmentCollection,
    "AssessmentObjectCollection": AssessmentObjectCollection,
    "AssessmentObjectTypeSummary": AssessmentObjectTypeSummary,
    "AssessmentObjectTypeSummaryCollection": AssessmentObjectTypeSummaryCollection,
    "AssessmentSummary": AssessmentSummary,
    "Assessor": Assessor,
    "AssessorAction": AssessorAction,
    "AssessorCheck": AssessorCheck,
    "AssessorCheckAction": AssessorCheckAction,
    "AssessorCheckGroup": AssessorCheckGroup,
    "AssessorCheckNameValue": AssessorCheckNameValue,
    "AssessorCheckSummary": AssessorCheckSummary,
    "AssessorCheckSummaryCollection": AssessorCheckSummaryCollection,
    "AssessorGroup": AssessorGroup,
    "AssessorSummary": AssessorSummary,
    "AssessorSummaryCollection": AssessorSummaryCollection,
    "ChangeAssessmentCompartmentDetails": ChangeAssessmentCompartmentDetails,
    "ChangeConnectionCompartmentDetails": ChangeConnectionCompartmentDetails,
    "ChangeMigrationCompartmentDetails": ChangeMigrationCompartmentDetails,
    "CloneAssessmentDetails": CloneAssessmentDetails,
    "CloneMigrationDetails": CloneMigrationDetails,
    "CollectTracesData": CollectTracesData,
    "CollectTracesDetails": CollectTracesDetails,
    "Connection": Connection,
    "ConnectionCollection": ConnectionCollection,
    "ConnectionSummary": ConnectionSummary,
    "CreateADBDedicatedAutoCreateTablespaceDetails": CreateADBDedicatedAutoCreateTablespaceDetails,
    "CreateADBDedicatedRemapTargetTablespaceDetails": CreateADBDedicatedRemapTargetTablespaceDetails,
    "CreateADBServerlesTablespaceDetails": CreateADBServerlesTablespaceDetails,
    "CreateAdminCredentials": CreateAdminCredentials,
    "CreateAssessmentDetails": CreateAssessmentDetails,
    "CreateConnectionDetails": CreateConnectionDetails,
    "CreateCurlTransferDetails": CreateCurlTransferDetails,
    "CreateDataPumpParameters": CreateDataPumpParameters,
    "CreateDirectoryObject": CreateDirectoryObject,
    "CreateExtract": CreateExtract,
    "CreateGoldenGateHubDetails": CreateGoldenGateHubDetails,
    "CreateHostDumpTransferDetails": CreateHostDumpTransferDetails,
    "CreateMigrationDetails": CreateMigrationDetails,
    "CreateMySqlAdvisorSettings": CreateMySqlAdvisorSettings,
    "CreateMySqlAssessmentDetails": CreateMySqlAssessmentDetails,
    "CreateMySqlDataTransferMediumDetails": CreateMySqlDataTransferMediumDetails,
    "CreateMySqlGgsDeploymentDetails": CreateMySqlGgsDeploymentDetails,
    "CreateMySqlInitialLoadSettings": CreateMySqlInitialLoadSettings,
    "CreateMySqlMigrationDetails": CreateMySqlMigrationDetails,
    "CreateMySqlObjectStorageDataTransferMediumDetails": CreateMySqlObjectStorageDataTransferMediumDetails,
    "CreateMysqlConnectionDetails": CreateMysqlConnectionDetails,
    "CreateNonADBAutoCreateTablespaceDetails": CreateNonADBAutoCreateTablespaceDetails,
    "CreateNonADBRemapTablespaceDetails": CreateNonADBRemapTablespaceDetails,
    "CreateObjectStoreBucket": CreateObjectStoreBucket,
    "CreateOciCliDumpTransferDetails": CreateOciCliDumpTransferDetails,
    "CreateOracleAdvisorSettings": CreateOracleAdvisorSettings,
    "CreateOracleAssessmentDetails": CreateOracleAssessmentDetails,
    "CreateOracleAwsS3DataTransferMediumDetails": CreateOracleAwsS3DataTransferMediumDetails,
    "CreateOracleConnectionDetails": CreateOracleConnectionDetails,
    "CreateOracleDataTransferMediumDetails": CreateOracleDataTransferMediumDetails,
    "CreateOracleDbLinkDataTransferMediumDetails": CreateOracleDbLinkDataTransferMediumDetails,
    "CreateOracleGgsDeploymentDetails": CreateOracleGgsDeploymentDetails,
    "CreateOracleInitialLoadSettings": CreateOracleInitialLoadSettings,
    "CreateOracleMigrationDetails": CreateOracleMigrationDetails,
    "CreateOracleNfsDataTransferMediumDetails": CreateOracleNfsDataTransferMediumDetails,
    "CreateOracleObjectStorageDataTransferMediumDetails": CreateOracleObjectStorageDataTransferMediumDetails,
    "CreateParameterFileVersionDetails": CreateParameterFileVersionDetails,
    "CreateReplicat": CreateReplicat,
    "CreateTargetTypeTablespaceDetails": CreateTargetTypeTablespaceDetails,
    "CurlTransferDetails": CurlTransferDetails,
    "DataPumpParameters": DataPumpParameters,
    "DatabaseConnectionTypeCollection": DatabaseConnectionTypeCollection,
    "DatabaseConnectionTypeSummary": DatabaseConnectionTypeSummary,
    "DatabaseInformation": DatabaseInformation,
    "DatabaseTechnologySubType": DatabaseTechnologySubType,
    "DatabaseTechnologyType": DatabaseTechnologyType,
    "DiagnosticsResult": DiagnosticsResult,
    "DirectoryObject": DirectoryObject,
    "DownloadSqlDetails": DownloadSqlDetails,
    "ExcludedObjectSummary": ExcludedObjectSummary,
    "ExcludedObjectSummaryCollection": ExcludedObjectSummaryCollection,
    "Extract": Extract,
    "GgsDeployment": GgsDeployment,
    "GoldenGateHubDetails": GoldenGateHubDetails,
    "HostDumpTransferDetails": HostDumpTransferDetails,
    "IngressIpDetails": IngressIpDetails,
    "Job": Job,
    "JobCollection": JobCollection,
    "JobOutputSummary": JobOutputSummary,
    "JobOutputSummaryCollection": JobOutputSummaryCollection,
    "JobSummary": JobSummary,
    "ListUpdateAdvisorReportCheckObjectsDetails": ListUpdateAdvisorReportCheckObjectsDetails,
    "ListUpdateCheckActionUpdateObjectDetails": ListUpdateCheckActionUpdateObjectDetails,
    "LogLocationBucketDetails": LogLocationBucketDetails,
    "MetadataRemap": MetadataRemap,
    "Migration": Migration,
    "MigrationCollection": MigrationCollection,
    "MigrationJobProgressResource": MigrationJobProgressResource,
    "MigrationJobProgressSummary": MigrationJobProgressSummary,
    "MigrationObjectCollection": MigrationObjectCollection,
    "MigrationObjectTypeSummary": MigrationObjectTypeSummary,
    "MigrationObjectTypeSummaryCollection": MigrationObjectTypeSummaryCollection,
    "MigrationParameterBase": MigrationParameterBase,
    "MigrationParameterDetails": MigrationParameterDetails,
    "MigrationParameterSummary": MigrationParameterSummary,
    "MigrationParameterSummaryCollection": MigrationParameterSummaryCollection,
    "MigrationPhaseCollection": MigrationPhaseCollection,
    "MigrationPhaseSummary": MigrationPhaseSummary,
    "MigrationSummary": MigrationSummary,
    "MySqlAdvisorSettings": MySqlAdvisorSettings,
    "MySqlAssessment": MySqlAssessment,
    "MySqlAssessmentObjectCollection": MySqlAssessmentObjectCollection,
    "MySqlAssessmentSummary": MySqlAssessmentSummary,
    "MySqlCloneAssessmentDetails": MySqlCloneAssessmentDetails,
    "MySqlCloneMigrationDetails": MySqlCloneMigrationDetails,
    "MySqlDataTransferMediumDetails": MySqlDataTransferMediumDetails,
    "MySqlDatabaseObject": MySqlDatabaseObject,
    "MySqlDatabaseObjectSummary": MySqlDatabaseObjectSummary,
    "MySqlGgsDeploymentDetails": MySqlGgsDeploymentDetails,
    "MySqlInitialLoadSettings": MySqlInitialLoadSettings,
    "MySqlMigration": MySqlMigration,
    "MySqlMigrationObjectCollection": MySqlMigrationObjectCollection,
    "MySqlMigrationSummary": MySqlMigrationSummary,
    "MySqlObjectStorageDataTransferMediumDetails": MySqlObjectStorageDataTransferMediumDetails,
    "MysqlConnection": MysqlConnection,
    "MysqlConnectionSummary": MysqlConnectionSummary,
    "NameValuePair": NameValuePair,
    "NonADBAutoCreateTablespaceDetails": NonADBAutoCreateTablespaceDetails,
    "NonADBRemapTablespaceDetails": NonADBRemapTablespaceDetails,
    "ObjectMetadata": ObjectMetadata,
    "ObjectStoreBucket": ObjectStoreBucket,
    "OciCliDumpTransferDetails": OciCliDumpTransferDetails,
    "OracleAdvisorSettings": OracleAdvisorSettings,
    "OracleAssessment": OracleAssessment,
    "OracleAssessmentObjectCollection": OracleAssessmentObjectCollection,
    "OracleAssessmentSummary": OracleAssessmentSummary,
    "OracleAwsS3DataTransferMediumDetails": OracleAwsS3DataTransferMediumDetails,
    "OracleCloneAssessmentDetails": OracleCloneAssessmentDetails,
    "OracleCloneMigrationDetails": OracleCloneMigrationDetails,
    "OracleConnection": OracleConnection,
    "OracleConnectionSummary": OracleConnectionSummary,
    "OracleDataTransferMediumDetails": OracleDataTransferMediumDetails,
    "OracleDatabaseObject": OracleDatabaseObject,
    "OracleDatabaseObjectSummary": OracleDatabaseObjectSummary,
    "OracleDbLinkDataTransferMediumDetails": OracleDbLinkDataTransferMediumDetails,
    "OracleGgsDeploymentDetails": OracleGgsDeploymentDetails,
    "OracleInitialLoadSettings": OracleInitialLoadSettings,
    "OracleMigration": OracleMigration,
    "OracleMigrationObjectCollection": OracleMigrationObjectCollection,
    "OracleMigrationSummary": OracleMigrationSummary,
    "OracleNfsDataTransferMediumDetails": OracleNfsDataTransferMediumDetails,
    "OracleObjectStorageDataTransferMediumDetails": OracleObjectStorageDataTransferMediumDetails,
    "ParameterFileVersion": ParameterFileVersion,
    "ParameterFileVersionCollection": ParameterFileVersionCollection,
    "ParameterFileVersionSummary": ParameterFileVersionSummary,
    "PerformAssessorActionDetails": PerformAssessorActionDetails,
    "PerformAssessorCheckActionDetails": PerformAssessorCheckActionDetails,
    "PhaseExtractEntry": PhaseExtractEntry,
    "PhaseStatus": PhaseStatus,
    "Replicat": Replicat,
    "ResultError": ResultError,
    "ResumeJobDetails": ResumeJobDetails,
    "SourceAssessmentConnection": SourceAssessmentConnection,
    "StartMigrationDetails": StartMigrationDetails,
    "TargetAssessmentConnection": TargetAssessmentConnection,
    "TargetTypeTablespaceDetails": TargetTypeTablespaceDetails,
    "UnsupportedDatabaseObject": UnsupportedDatabaseObject,
    "UpdateADBDedicatedAutoCreateTablespaceDetails": UpdateADBDedicatedAutoCreateTablespaceDetails,
    "UpdateADBDedicatedRemapTargetTablespaceDetails": UpdateADBDedicatedRemapTargetTablespaceDetails,
    "UpdateADBServerlesTablespaceDetails": UpdateADBServerlesTablespaceDetails,
    "UpdateAdminCredentials": UpdateAdminCredentials,
    "UpdateAdvisorReportCheckDetails": UpdateAdvisorReportCheckDetails,
    "UpdateAdvisorReportCheckObjectsDetails": UpdateAdvisorReportCheckObjectsDetails,
    "UpdateAssessmentDetails": UpdateAssessmentDetails,
    "UpdateCheckActionUpdateObjectDetails": UpdateCheckActionUpdateObjectDetails,
    "UpdateConnectionDetails": UpdateConnectionDetails,
    "UpdateCurlTransferDetails": UpdateCurlTransferDetails,
    "UpdateDataPumpParameters": UpdateDataPumpParameters,
    "UpdateDirectoryObject": UpdateDirectoryObject,
    "UpdateExtract": UpdateExtract,
    "UpdateGoldenGateHubDetails": UpdateGoldenGateHubDetails,
    "UpdateHostDumpTransferDetails": UpdateHostDumpTransferDetails,
    "UpdateJobDetails": UpdateJobDetails,
    "UpdateMigrationDetails": UpdateMigrationDetails,
    "UpdateMySqlAdvisorSettings": UpdateMySqlAdvisorSettings,
    "UpdateMySqlAssessmentDetails": UpdateMySqlAssessmentDetails,
    "UpdateMySqlDataTransferMediumDetails": UpdateMySqlDataTransferMediumDetails,
    "UpdateMySqlGgsDeploymentDetails": UpdateMySqlGgsDeploymentDetails,
    "UpdateMySqlInitialLoadSettings": UpdateMySqlInitialLoadSettings,
    "UpdateMySqlMigrationDetails": UpdateMySqlMigrationDetails,
    "UpdateMySqlObjectStorageDataTransferMediumDetails": UpdateMySqlObjectStorageDataTransferMediumDetails,
    "UpdateMysqlConnectionDetails": UpdateMysqlConnectionDetails,
    "UpdateNonADBAutoCreateTablespaceDetails": UpdateNonADBAutoCreateTablespaceDetails,
    "UpdateNonADBRemapTablespaceDetails": UpdateNonADBRemapTablespaceDetails,
    "UpdateObjectStoreBucket": UpdateObjectStoreBucket,
    "UpdateOciCliDumpTransferDetails": UpdateOciCliDumpTransferDetails,
    "UpdateOracleAdvisorSettings": UpdateOracleAdvisorSettings,
    "UpdateOracleAssessmentDetails": UpdateOracleAssessmentDetails,
    "UpdateOracleAwsS3DataTransferMediumDetails": UpdateOracleAwsS3DataTransferMediumDetails,
    "UpdateOracleConnectionDetails": UpdateOracleConnectionDetails,
    "UpdateOracleDataTransferMediumDetails": UpdateOracleDataTransferMediumDetails,
    "UpdateOracleDbLinkDataTransferMediumDetails": UpdateOracleDbLinkDataTransferMediumDetails,
    "UpdateOracleGgsDeploymentDetails": UpdateOracleGgsDeploymentDetails,
    "UpdateOracleInitialLoadSettings": UpdateOracleInitialLoadSettings,
    "UpdateOracleMigrationDetails": UpdateOracleMigrationDetails,
    "UpdateOracleNfsDataTransferMediumDetails": UpdateOracleNfsDataTransferMediumDetails,
    "UpdateOracleObjectStorageDataTransferMediumDetails": UpdateOracleObjectStorageDataTransferMediumDetails,
    "UpdateReplicat": UpdateReplicat,
    "UpdateTargetDefaultsAutoCreateTablespaceDetails": UpdateTargetDefaultsAutoCreateTablespaceDetails,
    "UpdateTargetDefaultsRemapTablespaceDetails": UpdateTargetDefaultsRemapTablespaceDetails,
    "UpdateTargetTypeTablespaceDetails": UpdateTargetTypeTablespaceDetails,
    "UserDefinedProperties": UserDefinedProperties,
    "UserDefinedProperty": UserDefinedProperty,
    "UserDefinedPropertyOption": UserDefinedPropertyOption,
    "WorkRequest": WorkRequest,
    "WorkRequestCollection": WorkRequestCollection,
    "WorkRequestError": WorkRequestError,
    "WorkRequestErrorCollection": WorkRequestErrorCollection,
    "WorkRequestLogEntry": WorkRequestLogEntry,
    "WorkRequestLogEntryCollection": WorkRequestLogEntryCollection,
    "WorkRequestResource": WorkRequestResource,
    "WorkRequestSummary": WorkRequestSummary
}
